namespace RdpRealTimePricing.Model.Enum
{
    public enum DomainEnum
    {
        MarketPrice,
        Analytics,
        Contribution,
        Dictionary,
        EconomicIndicator,
        Forecast,
        History,
        Headline,
        Login,
        MarketByOrder,
        MarketByPrice,
        MarketByTime,
        MarketMaker,
        NewsTextAnalytics,
        Poll,
        ProviderAdmin,
        ServiceProviderStatus,
        Source,
        Story,
        SymbolList,
        System,
        Reference,
        ReplayHeadline,
        ReplayStory,
        Transaction,
        YieldCurve
    };
}